build(deps): bump org.jetbrains.kotlin.jvm from 2.2.0 to 2.2.10 (#311)
Bumps [org.jetbrains.kotlin.jvm](https://github.com/JetBrains/kotlin)
from 2.2.0 to 2.2.10.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/JetBrains/kotlin/releases">org.jetbrains.kotlin.jvm's
releases</a>.</em></p>
<blockquote>
<h2>Kotlin 2.2.10-RC2</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79276"><code>KT-79276</code></a>
Dexing fails with &quot;Cannot read field X because <!-- raw HTML
omitted --> is null&quot; with 2.2.0</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79442"><code>KT-79442</code></a>
&quot;Multiple annotations of type
kotlin.coroutines.jvm.internal.DebugMetadata&quot;: 2.2.0-Beta1
generates broken code with JVM default suspend methods in
interfaces</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78815"><code>KT-78815</code></a>
<code>Symbol not found: __ZNSt3__117bad_function_callD1Ev</code> error
on iOS 15.5 simulator in Xcode 16.3 after update to 2.2.0-Beta2</li>
</ul>
<h3>JavaScript</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79050"><code>KT-79050</code></a>
KJS / IC: &quot;Unexpected body of primary constructor for processing
irClass&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79089"><code>KT-79089</code></a>
KJS: Could not load reporter / Cannot find module 'mocha' when running
jsNode tests</li>
</ul>
<h3>Native</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79075"><code>KT-79075</code></a>
Stuck on Kotlin_getSourceInfo_core_symbolication</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76178"><code>KT-76178</code></a>
LLVM Update: symbol '__ZnwmSt19__type_descriptor_t' missing</li>
</ul>
<h3>Tools. Kapt</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-79138"><code>KT-79138</code></a>
K2: KAPT Java Stub Gen: <code>Unresolved reference</code> with
<code>@kotlin</code>.Metadata in Java in 2.2.0</li>
</ul>
<h2>Kotlin 2.2.10-RC</h2>
<h2>Changelog</h2>
<h3>Compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78501"><code>KT-78501</code></a>
K2: Missing [ABSTRACT_SUPER_CALL] diagnostics for delegated interface
method leads to AssertionError: isCompiledToJvmDefault during IR
lowering</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78479"><code>KT-78479</code></a>
IR lowering failed / Unexpected null argument for composable call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76477"><code>KT-76477</code></a>
Kotlin/Native: fix compiler performance reporting in sources-&gt;klib
and klibs-&gt;binary</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78736"><code>KT-78736</code></a>
Missing [NOT_YET_SUPPORTED_IN_INLINE] diagnostics because of incorrect
context update</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77685"><code>KT-77685</code></a>
&quot;IllegalArgumentException: Sequence contains more than one matching
element&quot;</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-76365"><code>KT-76365</code></a>
K2: Missing ABSTRACT_SUPER_CALL</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78352"><code>KT-78352</code></a>
False-positive IDENTITY_SENSITIVE_OPERATIONS_WITH_VALUE_TYPE when
comparing with equality operator (==)</li>
</ul>
<h3>Compose compiler</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78479"><code>KT-78479</code></a>
Ensure that default transform affects functions entered through a
call</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78490"><code>KT-78490</code></a>
Fix visibility for default wrappers of protected methods</li>
<li><a
href="https://issuetracker.google.com/issues/408492167"><code>b/408492167</code></a>
Emit parameter names in Compose source information</li>
</ul>
<h3>Native. Runtime. Memory</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78925"><code>KT-78925</code></a>
Crash SIGABRT on Apple Watch after updating Kotlin to 2.2.0</li>
</ul>
<h3>Tools. CLI</h3>
<ul>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-77445"><code>KT-77445</code></a>
UNRESOLVED_REFERENCE when importing classes from kotlin-stdlib</li>
<li><a
href="https://youtrack.jetbrains.com/issue/KT-78263"><code>KT-78263</code></a>
java.lang.NoClassDefFoundError: Could not initialize class
com.intellij.psi.impl.PsiSubstitutorImpl</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/JetBrains/kotlin/commits">compare view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=org.jetbrains.kotlin.jvm&package-manager=gradle&previous-version=2.2.0&new-version=2.2.10)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>